version: '3.7'

services:
  searxng:
    container_name: semi_searxng
    image: searxng/searxng:latest
    networks:
      - searxng_net
    ports:
      - "8080:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8080/
    volumes:
      - ./searxng:/etc/searxng:rw
    restart: unless-stopped

networks:
  searxng_net:
    driver: bridge
